# Signal Aggregation Workflow Properties
nameNode=hdfs://telco-namenode:8020
resourceManager=telco-resourcemanager:8032
oozie.wf.application.path=${nameNode}/opt/telco/oozie/workflows/signal-aggregation

hive2_jdbc_url=jdbc:hive2://telco-hiveserver2:10000/default
hive_principal=hive/telco-hiveserver2@TELCO.COM

report_date=${coord:formatTime(coord:nominalTime(), 'yyyy-MM-dd')}
alert_email=noc-alerts@telco.com
